[package]
name = "dmsdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmsdk_ffi = { path = "../dmsdk_ffi" }
libc = "0.2.126"
paste = "1.0.7"
ctor = "0.1.23"

[dev-dependencies]
ctor = "0.1.22"