[package]
name = "extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmsdk = { git = "https://github.com/JustAPotota/defold-rs" }
base64 = "0.13.0"